config/routes.rb
Rails.application.routes.draw do
  
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
      
    }
 
	  namespace :admin do
      root 'games#index'

      resources :players
      resources :games do
        member do
          get 'assemble_game'
        end  
      end  
      #get 'games/:id/assemble_game' => "games#assemble_game"
      resources :winning_parts do 
        collection do
          post 'store_winning_part_cord'
        end  
      end  
      resources :winners ,only: [:index] 
    end

    root 'dashboard#index'

  get "api_help/index", :as => :api_help
  namespace :api, :defaults => {:format => 'json'} do
    scope :module => :v1 do
      post 'sign_up' => "users#sign_up",:as => :signup
      post 'login'  => 'users#login', :as => :login
      post 'update_profile' => 'users#update_profile', :as => :update_profile
      get  'logout' => 'users#logout', :as => :logout
      post 'change_password' => 'users#change_password'
      post 'forgot_password'   => 'users#forgot_password'
      get 'get_game_list' => 'games#get_list', :as => :get_game_list
      get 'search_game' => 'games#search_game', :as => :search_game
      post 'get_next_game_number' => 'games#get_next_game_number' , :as => :get_next_game_number  
      post 'get_room_user_list' => 'games#get_room_user_list' , :as => :get_room_user_list 
      post 'checking_winning_part' => 'games#checking_winning_part' , :as => :checking_winning_part
    end
  end
end

app/models/winning_part.rb
class WinningPart < ActiveRecord::Base
  belongs_to :game
  has_many :winners , :dependent => :destroy

  # to store array in coordinates field
  serialize :coordinates

  has_attached_file :image_part, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image_part, content_type: /\Aimage\/.*\Z/
end

app/controllers/admin/winning_parts_controller.rb
class Admin::WinningPartsController <  Admin::BaseController
  before_action :set_winning_part, only: [:show, :edit, :update, :destroy]

  # GET /diagnoses
  # GET /diagnoses.json
  def index
    @winning_parts = WinningPart.all
  end

  # GET /diagnoses/1
  # GET /diagnoses/1.json
  def show
  end

  # GET /diagnoses/new
  def new
    @winning_part = WinningPart.new
  end

  # GET /diagnoses/1/edit
  def edit
  end

  # POST /diagnoses
  # POST /diagnoses.json
  def create
    @winning_part = WinningPart.new(winning_parts_params)
    if @winning_part.save
        redirect_to admin_winning_part_path(@winning_part), :notice => "Winning Part was successfully created."
    else
      flash.now[:alert] = @winning_part.errors.full_messages
      render :new
    end
  end

  # PATCH/PUT /diagnoses/1
  # PATCH/PUT /diagnoses/1.json
  def update
    if @winning_part.update(winning_parts_params)
       redirect_to admin_winning_part_path(@winning_part), :notice => "WinningPart was successfully updated."
    else
      flash.now[:alert] = @winning_part.errors.full_messages
      render :edit
    end
  end

  # DELETE /diagnoses/1
  # DELETE /diagnoses/1.json
  def destroy
     @winning_part.destroy
    redirect_to admin_winning_parts_path, notice: 'Game was successfully destroyed.'
  end

  def store_winning_part_cord
    params.delete(:utf8)
    params.delete(:authenticity_token)
    params.delete(:controller)
    params.delete(:action)

    params.keys.each do |key|
      @winning_part = WinningPart.find(key)
      @winning_part.update_attributes(:coordinates  => params["#{key}"])
    end  
    redirect_to assemble_game_admin_game_path(@winning_part.game.id)
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_winning_part
      @winning_part = WinningPart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def winning_parts_params
        params.require(:winning_part).permit( :text_panel ,:num_of_element ,:part_color ,:game_id)
    end  


end

app/helpers/winning_parts_helper.rb
module WinningPartsHelper
end

app/views/admin/winning_parts/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">
      <div class="box-header">
        <% if @winning_part.new_record? %>
          <h3 class="box-title">New Winning Part</h3>
        <% else %>
          <h3 class="box-title">Edit Winning Part</h3>
        <% end %>
        <h3 class="box-title" style="float: right;"><%if request.url.include?("edit")%>  <%= link_to "Show", admin_winning_part_path(@winning_part), class: "label label-primary" %><% end  %>  <%= link_to "Back", admin_winning_parts_path, class: "label label-primary" %></h3>
          <%=  form_for([:admin,@winning_part], :html => {:id => "newPatientForm" , :multipart => true }  , :class => "bootstrap-validator-form") do |f| %>
            <div class="box-body col-md-6">

                <div class="form-group">
                  <label>Game</label>
                  <%= f.select :game_id ,options_from_collection_for_select(Game.all,:id, :name ,f.object.winning_part_game_id), {:include_blank => false},{:class => "form-control diagnosis_cls"} %>
                </div>

                <div class="form-group">
                  <label><%= f.label :text_panel%></label>
                  <%= f.text_field :text_panel, :class => "form-control" %>
                </div>

                <div class="form-group">
                  <label><%= f.label "Number Of Element" %></label>
                  <%= f.number_field :num_of_element , :class => "form-control"  %>
                </div>

                <div class="form-group">
                  <label>Color</label>
                   <%= f.text_field :part_color, :class => "form-control" %>
                </div>
                              
                <div class="box-footer col-md-6">
                  <%= f.submit class: "btn btn-primary" %>
                </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
      $("#winning_part_part_color").colorpicker();
      $("#winning_part_game_id").select2();
</script>

app/views/admin/winning_parts/edit.html.erb
<section class="content-header">
<h1>
  WinningPart
  <small>Edit</small>
</h1>
<ol class="breadcrumb">
  <li><%= link_to "<i class='fa fa-dashboard'></i> WinningPart".html_safe , admin_winning_parts_path  %></li>
  <li class="active">Edit</li>
</ol>
</section>

<section class="content">
  <%= render 'form' %>
</section>

app/views/admin/winning_parts/index.html.erb
<section class="content-header">
  <h1>
   Winning Parts
    <small>List</small>
  </h1>
  <ol class="breadcrumb">
    <li><%= link_to "<i class='fa fa-wheelchair'></i> WinningPart".html_safe , admin_winning_parts_path  %></li>
    <li class="active">List</li>
  </ol>
  <br />
  <%#= render 'shared/error_messages' %>
</section>

<section class="content">
<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">

      <div class="box-header">
        <h3 class="box-title">
           <%= link_to 'New WinningPart', new_admin_winning_part_path, class: "label label-primary" %>
        </h3>
        <br />
        <div class="box-body">
          <div class="table-responsive">
            <div id="example_wrapper" class="dataTables_wrapper" role="grid">
             
                
           <table id="game"  class="display" >
                <thead>
                    <th>Text_panel</th>
                    <th>Number of Element</th>
                    <th>Part COlor</th>
                   
                    <th colspan="3"></th>
                 </thead>
                <tbody>
                  <% @winning_parts.each do |winning_part| %>
                    <tr>
                      <td><%= winning_part.text_panel %></td>
                      <td><%= winning_part.num_of_element %></td>
                      <td><%= winning_part.part_color %></td>
                      <td><%= link_to 'Show', admin_winning_part_path(winning_part) %></td>
                      <td><%= link_to 'Edit', edit_admin_winning_part_path(winning_part) %></td>
                      <td><%= link_to 'Destroy', admin_winning_part_path(winning_part), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>

                </tbody>       
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>

app/views/admin/winning_parts/new.html.erb
<section class="content-header">
  <h1>
  	Game
    <small>New</small>
  </h1>
  <ol class="breadcrumb">
    <li><%= link_to "<i class='fa fa-files-o'></i> Admin Winning".html_safe , "#"  %></li>
    <li><%= link_to "<i class='fa fa-stethoscope'></i> Winning".html_safe , admin_winning_parts_path  %></li>
    <li class="active">New</li>
  </ol><br />
          <%#= render "shared/error_messages" %>
</section>
<section class="content">
	<%= render 'form' %>
</section>

app/views/admin/winning_parts/show.html.erb
<section class="content-header">
  <h1>
    WinningPart
    <small>Detail</small>
  </h1>
  <ol class="breadcrumb">
    <li><%= link_to "<i class='fa fa-dashboard'></i> WinningPart".html_safe , admin_winning_parts_path  %></li>
    <li class="active">Detail</li>
  </ol>
 </section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">
              <%= link_to 'Edit', edit_admin_winning_part_path(@winning_part), class: "label label-primary" %>
               <%= link_to "Back", :back, class: "label label-primary" %>
            </h3>   
        </div>
        <div class="box-body">
          <div class="table-responsive">
            <div id="example_wrapper" class="dataTables_wrapper" role="grid">
              <div class="dataTables_length" id="example_length">
              </div>
              <div id="example_filter" class="dataTables_filter pull-right">
              </div>
              <table aria-describedby="example_info" class="table table-bordered table-hover table-striped display dataTable" id="example">
                <thead>
                  <tr role="row">
                    <th aria-label="Business name: activate to sort column ascending" aria-sort="ascending" style="width: 178px;" colspan="1" rowspan="1" aria-controls="example" tabindex="0" role="columnheader"  > Text Color</th>
                    <td><%= @winning_part.text_panel %></td>
                  </tr>
              
                  <tr role="row">
                    <th aria-label="Business name: activate to sort column ascending" aria-sort="ascending" style="width: 178px;" colspan="1" rowspan="1" aria-controls="example" tabindex="0" role="columnheader"  >Game Type</th>
                    <td><%= @winning_part.num_of_element %></td>

                  </tr>
                  <tr role="row">
                    <th aria-label="Business name: activate to sort column ascending" aria-sort="ascending" style="width: 178px;" colspan="1" rowspan="1" aria-controls="example" tabindex="0" role="columnheader"  >Interval Sec</th>
                     <td><%= @winning_part.part_color %></td>

                  </tr>
                </thead>
              </table>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </div>
</section>
<br>