config/routes.rb
Rails.application.routes.draw do
  
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
      
    }
 
	  namespace :admin do
      root 'games#index'

      resources :players
      resources :games do
        member do
          get 'assemble_game'
        end  
      end  
      #get 'games/:id/assemble_game' => "games#assemble_game"
      resources :winning_parts do 
        collection do
          post 'store_winning_part_cord'
        end  
      end  
      resources :winners ,only: [:index] 
    end

    root 'dashboard#index'

  get "api_help/index", :as => :api_help
  namespace :api, :defaults => {:format => 'json'} do
    scope :module => :v1 do
      post 'sign_up' => "users#sign_up",:as => :signup
      post 'login'  => 'users#login', :as => :login
      post 'update_profile' => 'users#update_profile', :as => :update_profile
      get  'logout' => 'users#logout', :as => :logout
      post 'change_password' => 'users#change_password'
      post 'forgot_password'   => 'users#forgot_password'
      get 'get_game_list' => 'games#get_list', :as => :get_game_list
      get 'search_game' => 'games#search_game', :as => :search_game
      post 'get_next_game_number' => 'games#get_next_game_number' , :as => :get_next_game_number  
      post 'get_room_user_list' => 'games#get_room_user_list' , :as => :get_room_user_list 
      post 'checking_winning_part' => 'games#checking_winning_part' , :as => :checking_winning_part
    end
  end
end

app/controllers/admin/players_controller.rb
class Admin::PlayersController < Admin::BaseController
  before_action :set_admin_User, only: [:show, :edit, :update, :destroy]

  # GET /admin/Users
  # GET /admin/Users.json
  def index
    @admin_players = User.where(user_type: 2)
  end

  # GET /admin/Users/1
  # GET /admin/Users/1.json
  def show
  end

  # GET /admin/Users/new
  def new
    @admin_player = User.new
  end

  # GET /admin/Users/1/edit
  def edit
  end

  # POST /admin/Users
  # POST /admin/Users.json
  def create
    params[:user][:user_type] = 2 # user type for player
    @admin_player = User.new(admin_User_params)

    respond_to do |format|
      if @admin_player.save
        format.html { redirect_to admin_players_path, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @admin_User }
      else
        flash[:error] = @admin_player.errors.full_messages
        format.html { render :new }
        format.json { render json: @admin_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/Users/1
  # PATCH/PUT /admin/Users/1.json
  def update
    respond_to do |format|
      if @admin_player.update(admin_User_params)
        format.html { redirect_to admin_player_path(@admin_player) , notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_User }
      else
        flash[:error] = @admin_player.errors.full_messages
        format.html { render :edit }
        format.json { render json: @admin_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/Users/1
  # DELETE /admin/Users/1.json
  def destroy
    @admin_player.destroy
    respond_to do |format|
      format.html { redirect_to admin_players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_User
      @admin_player = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_User_params
      params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation,:user_type)
    end
end

app/views/admin/players/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">
      <div class="box-header"> 
      <% text = @admin_player.new_record? ? "New Player" : "Edit Player" %>
      <% btn_text = @admin_player.new_record? ? "Create New Player" : "Update Player" %>
          <h3 class="box-title"><%=text %></h3>
        <h3 class="box-title" style="float: right;"><%if request.url.include?("edit")%>  <%= link_to "Show", admin_player_path(@admin_player), class: "label label-primary" %><% end  %>  <%= link_to "Back", admin_players_path, class: "label label-primary" %></h3>

          <% path = @admin_player.new_record? ? admin_players_path : admin_player_path %>
          <%= form_for(@admin_player ,:url => path,:html => {:id => "newPlayerForm"}, :class => "bootstrap-validator-form") do |f| %>

            <div class="box-body col-md-6">
                <div class="form-group">
                  <label><%= f.label :email%></label>
                  <%= f.email_field :email, :class => "form-control" %>
                </div>
                <!-- <div class="form-group">
                  <label><%#= f.label :game_type %></label>
                  <%#= f.number_field :game_type , :class => "form-control"  %>
                </div> -->
                <div class="form-group">
                  <label><%= f.label "First Name" %></label>
                  <%= f.text_field :first_name , :class => "form-control"  %>
                </div>
                <!-- <div class="form-group">
                  <label><%#= f.label :total_number_in_ticket %></label>
                  <%#= f.number_field :total_number_in_ticket , :class => "form-control"  %>
                </div> -->
                <div class="form-group">
                  <label><%= f.label "Last Name" %></label>
                  <%= f.text_field :last_name , :class => "form-control"  %>
                </div>
                <div class="form-group">
                  <label><%= f.label "Password" %></label>
                  <%= f.password_field :password , :class => "form-control"  %>
                </div> 
                <div class="form-group">
                  <label><%= f.label "Password Confirmation" %></label>
                  <%= f.password_field :password_confirmation , :class => "form-control"  %>
                </div>                                     
                <div class="box-footer col-md-6">
                  <%= f.submit class: "btn btn-primary" ,:value => "#{btn_text}" %>
                </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/players/edit.html.erb
<section class="content-header">
<h1>
  Player
  <small>Edit</small>
</h1>
<ol class="breadcrumb">
  <li><%= link_to "<i class='fa fa-dashboard'></i> Player".html_safe , admin_players_path  %></li>
  <li class="active">Edit</li>
</ol>
</section>

<section class="content">
  <%= render 'form' %>
</section>

app/views/admin/players/index.html.erb
<section class="content-header">
  <h1>
    Players
    <small>List</small>
  </h1>
  <ol class="breadcrumb">
    <li><%= link_to "<i class='fa fa-wheelchair'></i> Game".html_safe , admin_players_path  %></li>
    <li class="active">List</li>
  </ol>
  <br />
  <%#= render 'shared/error_messages' %>
</section>

<section class="content">
<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">

      <div class="box-header">
        <h3 class="box-title">
           <%= link_to 'New Player', new_admin_player_path, class: "label label-primary" %>
        </h3>
        <br />
        <div class="box-body">
          <div class="table-responsive">
            <div id="example_wrapper" class="dataTables_wrapper" role="grid">
             

              <table id="game"  class="display" style="width:100%;">
                <thead>
                  <tr>
                    <th>Email</th>
                    <th>First name</th>
                    <th>Last name</th>
                <!--    <th>Password</th>
                    <th>Password confirmation</th> -->
                    <th colspan="3"></th>
                  </tr>
                </thead>

                <tbody>
                  <% @admin_players.each do |admin_player| %>
                    <tr>
                      <td><%= admin_player.email %></td>
                      <td><%= admin_player.first_name %></td>
                      <td><%= admin_player.last_name %></td>
                    <!--  <td><%#= admin_player.password %></td>
                      <td><%#= admin_player.password_confirmation %></td> -->
                      <td><%= link_to 'Show', admin_player_path(admin_player) %></td>
                      <td><%= link_to 'Edit', edit_admin_player_path(admin_player) %></td>
                      <td><%= link_to 'Destroy', admin_player_path(admin_player), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>

app/views/admin/players/new.html.erb
<section class="content-header">
  <h1>
  	Player
    <small>New</small>
  </h1>
  <ol class="breadcrumb">
    <li><%= link_to "<i class='fa fa-files-o'></i> Admin Game".html_safe , "#"  %></li>
    <li><%= link_to "<i class='fa fa-stethoscope'></i> Players".html_safe , admin_players_path  %></li>
    <li class="active">New</li>
  </ol><br />
  <%#= render "shared/error_messages" %>
</section>
<section class="content">
	<%= render 'form' %>
</section>

app/views/admin/players/show.html.erb
<section class="content-header">
  <h1>
    Games
    <small>Detail</small>
  </h1>
  <ol class="breadcrumb">
    <li><%= link_to "<i class='fa fa-dashboard'></i> games".html_safe , admin_players_path  %></li>
    <li class="active">Detail</li>
  </ol>
 </section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">
              <%= link_to 'Edit', edit_admin_player_path(@admin_player), class: "label label-primary" %>
               <%= link_to "Back", :back, class: "label label-primary" %>
            </h3>   
        </div>
        <div class="box-body">
          <div class="table-responsive">
            <div id="example_wrapper" class="dataTables_wrapper" role="grid">
              <div class="dataTables_length" id="example_length">
              </div>
              <div id="example_filter" class="dataTables_filter pull-right">
              </div>
              <table aria-describedby="example_info" class="table table-bordered table-hover table-striped display dataTable" id="example">
                <thead>
                  <tr role="row">
                    <th aria-label="Business name: activate to sort column ascending" aria-sort="ascending" style="width: 178px;" colspan="1" rowspan="1" aria-controls="example" tabindex="0" role="columnheader"  > Email</th>
                    <td><%= @admin_player.email %></td>
                  </tr>
              
                  <tr role="row">
                    <th aria-label="Business name: activate to sort column ascending" aria-sort="ascending" style="width: 178px;" colspan="1" rowspan="1" aria-controls="example" tabindex="0" role="columnheader"  >First Name</th>
                    <td><%= @admin_player.first_name %></td>

                  </tr>
             
                  <tr role="row">
                    <th aria-label="Business name: activate to sort column ascending" aria-sort="ascending" style="width: 178px;" colspan="1" rowspan="1" aria-controls="example" tabindex="0" role="columnheader"  >Last name</th>
                     <td><%= @admin_player.last_name %></td>

                  </tr>

                </thead>
              </table>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </div>
</section>
<br>