config/routes.rb
Rails.application.routes.draw do
  
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
      
    }
 
	  namespace :admin do
      root 'games#index'

      resources :players
      resources :games do
        member do
          get 'assemble_game'
        end  
      end  
      #get 'games/:id/assemble_game' => "games#assemble_game"
      resources :winning_parts do 
        collection do
          post 'store_winning_part_cord'
        end  
      end  
      resources :winners ,only: [:index] 
    end

    root 'dashboard#index'

  get "api_help/index", :as => :api_help
  namespace :api, :defaults => {:format => 'json'} do
    scope :module => :v1 do
      post 'sign_up' => "users#sign_up",:as => :signup
      post 'login'  => 'users#login', :as => :login
      post 'update_profile' => 'users#update_profile', :as => :update_profile
      get  'logout' => 'users#logout', :as => :logout
      post 'change_password' => 'users#change_password'
      post 'forgot_password'   => 'users#forgot_password'
      get 'get_game_list' => 'games#get_list', :as => :get_game_list
      get 'search_game' => 'games#search_game', :as => :search_game
      post 'get_next_game_number' => 'games#get_next_game_number' , :as => :get_next_game_number  
      post 'get_room_user_list' => 'games#get_room_user_list' , :as => :get_room_user_list 
      post 'checking_winning_part' => 'games#checking_winning_part' , :as => :checking_winning_part
    end
  end
end

app/models/game.rb
class Game < ActiveRecord::Base

	# game_type : 1 for characters and game_type : 2 for numbers 

	has_many :rooms ,:dependent => :destroy
	has_many :winning_parts ,:dependent => :destroy

	has_attached_file :game_image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :game_image, content_type: /\Aimage\/.*\Z/

  accepts_nested_attributes_for :winning_parts ,:allow_destroy => true 
  validates :name, :interval_sec, :num_of_player, :game_image, presence: true
  validate :seconds_greater_than
  validate :num_of_player_count
  validate :valid_game_image


	def valid_game_image
  	if self.game_image.present? && self.game_image.queued_for_write[:original].present? 
    		dimensions = Paperclip::Geometry.from_file(self.game_image.queued_for_write[:original])
    		self.errors.add(:game_image, "Please upload a file at least 600 pixels wide") if dimensions.width > 600.to_f
    		self.errors.add(:game_image, "Please upload a file at least 600 pixels tall") if dimensions.height > 600.to_f
  	end
	end

  private
  def seconds_greater_than
    if self.interval_sec && (self.interval_sec < 10)
      self.errors.add(:interval_sec, "Minimum 10 Seconds Interval is Compulsory.")
    end
  end

  def num_of_player_count
    if self.num_of_player && (self.num_of_player < 2)
      self.errors.add(:num_of_player, "Minimum 2 players are Compulsory.")
    end
  end

end

app/controllers/admin/games_controller.rb
class  Admin::GamesController <  Admin::BaseController
 before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /diagnoses
  # GET /diagnoses.json
  def index
    @games = Game.all
  end

  # GET /diagnoses/1
  # GET /diagnoses/1.json
  def show
  end

  # GET /diagnoses/new
  def new
    @game = Game.new
    @game.winning_parts.build
  end

  # GET /diagnoses/1/edit
  def edit
  end

  # POST /diagnoses
  # POST /diagnoses.json
  def create
    @game = Game.new(games_params)
    if @game.save
        redirect_to admin_game_path(@game), :notice => "Game was successfully created."
    else
      flash.now[:alert] = @game.errors.full_messages
      render :new
    end
  end

  # PATCH/PUT /diagnoses/1
  # PATCH/PUT /diagnoses/1.json
  def update
    if @game.update(games_params)
       redirect_to admin_game_path(@game), :notice => "Game was successfully updated."
    else
      flash.now[:alert] = @game.errors.full_messages
      render :edit
    end
  end

  # DELETE /diagnoses/1
  # DELETE /diagnoses/1.json
  def destroy
     @game.destroy
    redirect_to admin_games_path, notice: 'Game was successfully destroyed.'
  end

  def assemble_game
    @game = Game.find(params[:id])
    #redirect_to assemble_game_admin_game_path(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def games_params
        params.require(:game).permit( :name ,:game_type ,:interval_sec ,:total_number_in_ticket ,:num_of_player,:game_image ,:description , winning_parts_attributes: [:id, :text_panel, :num_of_element ,:part_color, :_destroy])
    end
end

app/controllers/api/v1/games_controller.rb
class Api::V1::GamesController < Api::V1::BaseController
	before_filter :authentication_user_with_authentication_token, :only => [:get_list, :search_game ,:get_next_game_number,:get_room_user_list,:checking_winning_part]

	def get_list
		@token = AuthenticationToken.current_authentication_token_for_user(@current_user.id,params[:authentication_token]).first
		if @token.present?
			@games = Game.all.includes(:winning_parts)
			
			unless @games.present?
				render_json({:errors => "No games present"}.to_json)
			end
		else
			render_json({:errors => "No user found with authentication_token = #{params[:authentication_token]}"}.to_json)
		end
	end

	def search_game
		@token = AuthenticationToken.current_authentication_token_for_user(@current_user.id,params[:authentication_token]).first
		if @token.present?
			@game = Game.find(params[:game_id])
			limit = 0
			limit = @game.winning_parts.map(&:num_of_element).inject(0){|sum,x| sum+x}
			@rooms = Room.where("game_id = ? and created_at > ? and status = ?", @game.id, Time.now - 1.minutes, "Active")
			if @rooms.present?
				puts "=====================+Room Present+====#{@rooms.first.tickets.count}=================="
				@room = @rooms.first
				@ticket = @room.tickets.find_by(:user_id => @current_user.id)
				if !@ticket.present?
					@ticket = @room.tickets.build(:user_id => @current_user.id ,:num_array => generate_tickets(limit))
					@ticket.save
				end
				puts "==================Ticket=========#{@ticket.inspect}"
				if @rooms.first.tickets.count == @game.num_of_player
					@rooms.first.status = "Deactive"
					@rooms.first.save
					@room = @rooms.first
				end
			else
				puts "===============+New Room+=================="
		        generate_rooms
		        @ticket = @room.tickets.find_by(:user_id => @current_user.id)
				if !@ticket.present?
		        	@ticket = @room.tickets.build(:user_id => @current_user.id ,:num_array => generate_tickets(limit))
		        	@ticket.save
		        end
		        puts "==================Ticket=========#{@ticket.inspect}"
			end
			@part_counts = @room.game.winning_parts.map(&:num_of_element)

		else	
		end
	end

	def generate_tickets(limit)
		numbers = []
		loop do
			break if numbers.size == limit
      x = rand(25)
      unless numbers.include? x
      	numbers << x
      end
    end
    return numbers
	end	

	def generate_rooms
		number_of_array = (0..24).to_a.shuffle
		@room = @game.rooms.build(status: "Active", deactivation_time: Time.now + 1.minutes , num_array_to_pass: number_of_array)
		@room.save
		# scheduler.at @room.deactivation_time do
		# 	total_numbers = []
		# 	scheduler.every '#{@game.interval_sec.to_i}s' do
		# 		x = rand(100)
		# 		if @room.num_array_to_pass.size < 100 && !@room.include? x
		# 		else
		# 		end
		# 	end
		# end
		return @room
	end	

	def get_next_game_number
		@token = AuthenticationToken.current_authentication_token_for_user(@current_user.id,params[:authentication_token]).first
		if @token.present?
			@tickets = Ticket.where(:room_id => params[:room_id])
			if @tickets.count == 1
				@tickets.first.room.update_attributes(:status => "Active", deactivation_time: Time.now + 1.minutes)	
				render_json({:result=>{:errors => "Please wait for sometime as you are the only one player.", :game_start_time => @tickets.first.room.deactivation_time}}.to_json)
			else
				@room = @current_user.tickets.find_by(:room_id => params[:room_id]).room
				if @room.present?
					if @room.num_array_to_pass.present?
						if params[:current_head].to_i == 25	
	 						render_json({:result=>{ :errors => "Game is over"}}.to_json)
	 					else
							@number = @room.num_array_to_pass[params[:current_head].to_i]
							puts "#{@number}------------------==========="
							@winners = @room.winners
	 					end
	 				else
						render_json({:result=>{:errors => "Please wait for some time to get the next number"}}.to_json)
					end
				else
					render_json({:result=>{:errors => "sorry room is not found"}}.to_json)
				end
			end 

		else
			render_json({:errors => "No user found with authentication_token = #{params[:authentication_token]}"}.to_json)
		end
	end 


	def get_room_user_list
		@token = AuthenticationToken.current_authentication_token_for_user(@current_user.id,params[:authentication_token]).first
		if @token.present?
			@tickets =  Ticket.where(:room_id => params[:room_id].to_i)
			puts "-------------#{@tickets.count}"
			if !@tickets.present?
				render_json({:errors => "sorry room is not found"}.to_json)
			end
		else
			render_json({:errors => "No user found with authentication_token = #{params[:authentication_token]}"}.to_json)
		end

	end  

	def checking_winning_part
		@token = AuthenticationToken.current_authentication_token_for_user(@current_user.id,params[:authentication_token]).first
		if @token.present?
			elements_to_find = params[:elements_list].split(",")
			puts "=================#{elements_to_find.inspect}"
			puts "====Room ID===#{params[:room_id].inspect}"
			current_index = params[:current_index].to_i
			puts "=======+Current Index======#{current_index}"
			@elemt  = []
			@counter = 0
			displayed_elements = Room.find(params[:room_id].to_i).num_array_to_pass[0..current_index]
			puts "====Total Array===#{Room.find(params[:room_id]).num_array_to_pass.inspect}"
			puts "========DisPayed Array======#{displayed_elements.inspect}"
			# if elements_to_find.count == current_index 
				puts "=============================AHIYAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			
				if params[:winning_part_id].to_i == 0
					if (elements_to_find - displayed_elements).empty?
						@current_user.winners.build(:room_id => params[:room_id]).save
						render_json({:result=>{:messages =>"Ok",:rstatus=>1, :errorcode =>""},:data=>{:messages =>"you completed fullhouse game successfully" }}.to_json)			
					else
						render_json({:result => {:errors => "Winning part not completed properly due to elemets" ,:disqualify => true}}.to_json)
					end
				else
					winning_part = WinningPart.find(params[:winning_part_id])
					if (elements_to_find - displayed_elements).empty?
						@current_user.winners.build(:winning_part_id => winning_part.id,:room_id => params[:room_id]).save
						render_json({:result=>{:messages =>"Ok",:rstatus=>1, :errorcode =>""},:data=>{:messages =>"you completed #{winning_part.text_panel} successfully" }}.to_json)			
					else
						render_json({:result =>{:errors => "Winning part not completed properly due to elemets",:disqualify => true}}.to_json)
					end
				end
			# else
			# 	render_json({:result => {:errors => "Winning part not completed properly due to elemets #{@elem}" ,:disqualify => true}}.to_json)
			# end			
		else
			render_json({:result => {:errors => "No user found with authentication_token = #{params[:authentication_token]}"}}.to_json)
		end
	end	

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/admin/games/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">
      <div class="box-header">
        <% if @game.new_record? %>
          <h3 class="box-title">New Game</h3>
        <% else %>
          <h3 class="box-title">Edit Game</h3>
        <% end %>
        <h3 class="box-title" style="float: right;"><%if request.url.include?("edit")%>  <%= link_to "Show", admin_game_path(@game), class: "label label-primary" %><% end  %>  <%= link_to "Back", admin_games_path, class: "label label-primary" %></h3>
          <%=  nested_form_for([:admin,@game], :html => {:id => "newPatientForm" ,multipart: true }, :class => "bootstrap-validator-form") do |f| %>
            <div class="box-body col-md-6">
                <div class="form-group">
                  <label><%= f.label :name%></label>
                  <%= f.text_field :name, :class => "form-control" %>
                </div>

                <div class="form-group">
                  <label><%= f.label :description%></label>
                  <%= f.text_area :description, :class => "form-control" %>
                </div>
     
                <div class="form-group">
                  <label><%= f.label "Interval In Seconds" %></label>(Please Enter mininum 10 sec)
                  <%= f.number_field :interval_sec , :class => "form-control"  %>
                </div>
         
                <div class="form-group">
                  <label><%= f.label "Maximum Number Of Players" %></label>
                  <%= f.number_field :num_of_player , :class => "form-control"  %>
                </div>    

                <div class="form-group">
                  <label><%= f.label "Game Image" %></label>(Please Enter the image size upto 600x600)
                  <%= f.file_field :game_image , :class => "form-control"  %>
                </div>    

                <div class="form-group">               
                  <%= f.fields_for :winning_parts  %>
                  <%= f.link_to_add "Add a Winning Parts", :winning_parts %></p>
                </div>    


                <div class="box-footer col-md-6">
                  <%= f.submit class: "btn btn-primary" %>
                </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>



<script type="text/javascript">

  remove_count = 0 ;

  function add_count_remove()
  {
      remove_count += 1;
  }
  if (remove_count == 0)
  {
    $(".remove_link").hide();
  }

</script>

app/views/admin/games/_winning_part_fields.html.erb
<div class="box box-primary">
  <div class="box-header">
  <div class="form-group">
    <label><%= f.label :text_panel%></label>
    <%= f.text_field :text_panel, :class => "form-control" %>
  </div>
  <div class="form-group">
    <label><%= f.label "Number Of Element" %></label>
    <%= f.number_field :num_of_element , :class => "form-control"  %>
  </div>

  <div class="form-group">
   <label><%= f.label "Color" %></label>
     <%= f.text_field :part_color, :class => "form-control part_color" %>
  </div>

  <div class="remove_link">
  	<%= f.link_to_remove "Remove This Winning Part" ,:onclick => "remove_remove_link()"%>
  </div> 
  </div>
</div>
<script type="text/javascript">
      $(".part_color").colorpicker();
</script>


<script type="text/javascript">

$( document ).ready(function() {
    remove_count += 1
    if (remove_count == 1)
    {
      $(".remove_link").hide();
    }
    else
    {
      $(".remove_link").show();
    }
   }); 
function remove_remove_link(){
  
  remove_count = remove_count - 1;
  if (remove_count == 1)
  {
    $(".remove_link").hide();
  }
  else
  {
    $(".remove_link").show();
  }
}

</script>

app/views/admin/games/assemble_game.html.erb
<style type="text/css">

    .dragme {
        position:relative;
     /*   width: 270px;
        height: 373px; */
        cursor: move;
        background-color: #ccc;
        border: 1px solid #000;

        height: 40px;
        width: 40px;
        z-index: 100;
        -moz-border-radius: 20px;
        border-radius: 20px;
    }
    #draggable {
        background-color: #ccc;
        border: 1px solid #000;
    }

    .elementCls {
      position:relative;
      height: 40px;
      width: 40px;
      z-index: 100;
    }
</style>

<section class="content-header">
  <h1>
    Assemble
    <small>Game</small>
  </h1>

  <br />
</section>
<section class="content">
<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">
      
      <div class="box-header" style="padding: 0px !important;">
        <div class="box-body" id="boardId" style="padding: 0px !important;" >
<!--          <img src="<%= @game.game_image.url %>" alt="drag-and-drop image script" 
 title="drag-and-drop image script" class="dragme" id="img1Id"> -->
          <img src="<%= @game.game_image.url %>" alt="drag-and-drop image script" 
 title="drag-and-drop image script" id="img1Id"  style="float:left; max-width:600px;">
        <%= form_tag store_winning_part_cord_admin_winning_parts_path , :id => "store_cords" do %>
          <div style="float:left; width:30%;margin:20px;">
            <% @game.winning_parts.each do |parts| %>
                <div class="elementCls" style="background:<%= parts.part_color %>;width:20%;float:left;margin-bottom:10px;"> </div> <span style="width:80%;float:left;height:40px;margin-bottom:10px;padding-left:10px;"> Set in <%= parts.text_panel %> </span> 
            <% end %>  
          </div>
          <% @game.winning_parts.each do |parts| %>
            <%= hidden_field_tag parts.id , ""%>
            <% (1..parts.num_of_element).to_a.each_with_index do |index| %>
              <div class="dragme <%= parts.id %>" title="drag-and-drop image script" draggable="true" style="background:<%= parts.part_color %>;"> </div>
            <!--
              <%# if parts.coordinates.nil? %>
                <div class="dragme <%#= parts.id %>" title="drag-and-drop image script" draggable="true" style="background:<%#= parts.part_color %>;"> </div>
              <%# else %>
                <%# coord = parts.coordinates.split(",") %>
                <div class="dragme <%#= parts.id %>" title="drag-and-drop image script" draggable="true" style="background:<%#= parts.part_color %>; left: <%#= coord[index*2 - 2] %>px; top: <%#= coord[index*2 - 1] %>px;"> </div>
              <%# end %>
            -->
             
            <% end %>
          <% end %>
          <% end %>
        </div>
        <!-- 
          <a href="#" onclick="addElement(this.id)" id="red" > Add Element Red </a>
          <a href="#" onclick="addElement(this.id)" id="green" > Add Element Green </a>
        -->
      </div>
      <div class="text-center pad-btm-20">
        <button type="button" onclick="saveElementPosition()" class="btn btn-primary">Save</button> 
      <%#=button_to "Save" ,:class=> "btn btn-primary txt-center",:onclick => "saveElementPosition()"  %>
      </div>
    
    </div>
  </div>
</div>
</section>

<script type="text/javascript">

        function saveElementPosition(){
          //alert("Save");
          
          <% @game.winning_parts.each do |parts| %>
            var arr_cords = new Array();
              $('.dragme.<%= parts.id %>').each(function(i, obj) {
                //test
                arr_cords.push([obj.offsetLeft,obj.offsetTop])
                
                //console.log("offset left" +obj.offsetLeft)
                //console.log("offset right" +obj.offsetTop)
                //alert(arr_cords)
                //alert("#<%=parts.id %>");
                //$("#<%=parts.id %>").val = arr_cords

              });
              hiddenFields = document.getElementById("<%= parts.id %>");
              //alert(arr_cords)
              hiddenFields.value = arr_cords
          <% end %>
          $("#store_cords").submit();
        }
        /*
        function set_cord_location(){  
          <%# @game.winning_parts.each do |parts| %>
            <%# coords =  !parts.coordinates.nil? ? parts.coordinates.split(",") : [] %>
            <%# @count = 0 %>
            $('.dragme.<%#= parts.id %>').each(function(i, obj) {
              //alert("count<%#=@count %>")
              //alert(<%#= coords[@count] %>)
              $(this).css({top: <%#= coords[@count] %>, left: <%#= coords[@count+1] %>})
              <%# @count = @count + 2 %>
            });
          <%# end %> 
        }
        set_cord_location(); 
        */
        /*
      function set_cord_location(){  
        <%# @game.winning_parts.each do |parts| %>
          <%# coords =  parts.coordinates.split(",") %>
          <%# @count = 0 %>
          $('.dragme.<%#= parts.id %>').each(function(i, obj) {
            alert("count<%#=@count %>")
           alert(<%#= coords[@count] %>)
          $(this).css({top: <%#= coords[@count] %>, left: <%#= coords[@count+1] %>})
          <%# @count = @count  + 2 %>
        })
        <%# end %> 
      }
      set_cord_location();
      
        /*
        function addElement(elementId){
            //alert(elementId);
            board = document.getElementById("boardId");
            
            var d = document.createElement( 'div' );
            d.id = "id_" + elementId + 1;
            d.className = "elementCls";
            //board.innerHTML =  d;
            //d.innerHTML = i.innerHTML ;

            board.appendChild(d);
            document.onmousedown = startDrag;
            document.onmouseup = stopDrag;
        } */


        function startDrag(e) {
            // determine event object
            if (!e) {
                var e = window.event;
            }

            // IE uses srcElement, others use target
            var targ = e.target ? e.target : e.srcElement;

            //if (targ.className != 'dragme') {return};
            if (!targ.className.includes('dragme')) {return};
            // calculate event X, Y coordinates
                offsetX = e.clientX;
                offsetY = e.clientY;

            // assign default values for top and left properties
            if(!targ.style.left) { targ.style.left='0px'};
            if (!targ.style.top) { targ.style.top='0px'};

            // calculate integer values for top and left 
            // properties
            coordX = parseInt(targ.style.left);
            coordY = parseInt(targ.style.top);
            drag = true;

            // move div element
                document.onmousemove=dragDiv;

        }
        function dragDiv(e) {
            if (!drag) {return};
            if (!e) { var e= window.event};
            var targ=e.target?e.target:e.srcElement;
            t = targ;
            // move div element
            targ.style.left=coordX+e.clientX-offsetX+'px';
            targ.style.top=coordY+e.clientY-offsetY+'px';
            return false;
        }
        function stopDrag() {
            drag=false;
            a = document.getElementById("img1Id");
            //alert("X: " + a.offsetLeft + ", Y: " + a.offsetTop);
        }
        window.onload = function() {
            document.onmousedown = startDrag;
            document.onmouseup = stopDrag;
        }


</script>

app/views/admin/games/edit.html.erb
<section class="content-header">
<h1>
  Game
  <small>Edit</small>
</h1>
<ol class="breadcrumb">
  <li><%= link_to "<i class='fa fa-dashboard'></i> Physicians".html_safe , admin_games_path  %></li>
  <li class="active">Edit</li>
</ol>
</section>

<section class="content">
  <%= render 'form' %>
</section>

app/views/admin/games/index.html.erb
<section class="content-header">
  <h1>
    Games
    <small>List</small>
  </h1>
  <ol class="breadcrumb">
    <li><%= link_to "<i class='fa fa-wheelchair'></i> Game".html_safe , admin_games_path  %></li>
    <li class="active">List</li>
  </ol>
  <br />
  <%#= render 'shared/error_messages' %>
</section>

<section class="content">
<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">

      <div class="box-header">
        <h3 class="box-title">
           <%= link_to 'New Game', new_admin_game_path, class: "label label-primary" %>
        </h3>
        <br />
        <div class="box-body">
          <div class="table-responsive">
            <div id="example_wrapper" class="dataTables_wrapper" role="grid">
             
                
           <table id="game"  class="display" style="width:100%;" >
                <thead>
                    <th>Name</th>
                  <!--  <th>Game type</th> -->
                    <th>Interval in sec</th>
                  <!--  <th>Total num in ticket</th>  -->
                    <th>Num of player</th>
                    <th colspan="4"></th>
                 </thead>
                <tbody>
                  <% @games.each do |game| %>
                    <tr>
                      <td><%= game.name %></td>
                    <!--  <td><%#= game.game_type %></td> -->
                      <td><%= game.interval_sec %></td>
                    <!--  <td><%#= game.total_number_in_ticket %></td>  -->
                      <td><%= game.num_of_player %></td>
                      <td><%= link_to 'Show', admin_game_path(game) %></td>
                      <td><%= link_to 'Edit', edit_admin_game_path(game) %></td>
                      <td><%= link_to 'Destroy', admin_game_path(game), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                      <td><%= link_to 'Set Element', assemble_game_admin_game_path(game.id) %> </td>
                    </tr>
                  <% end %>

                </tbody>       
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>

app/views/admin/games/new.html.erb
<section class="content-header">
  <h1>
  	Game
    <small>New</small>
  </h1>
  <ol class="breadcrumb">
    <li><%= link_to "<i class='fa fa-files-o'></i> Admin Game".html_safe , "#"  %></li>
    <li><%= link_to "<i class='fa fa-stethoscope'></i> Games".html_safe , admin_games_path  %></li>
    <li class="active">New</li>
  </ol><br />
          <%#= render "shared/error_messages" %>
</section>
<section class="content">
	<%= render 'form' %>
</section>

app/views/admin/games/show.html.erb
<section class="content-header">
  <h1>
    Games
    <small>Detail</small>
  </h1>
  <ol class="breadcrumb">
    <li><%= link_to "<i class='fa fa-dashboard'></i> games".html_safe , admin_games_path  %></li>
    <li class="active">Detail</li>
  </ol>
 </section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">
              <%= link_to 'Edit', edit_admin_game_path(@game), class: "label label-primary" %>
               <%= link_to "Back", :back, class: "label label-primary" %>
               <%= link_to 'Set Element', assemble_game_admin_game_path(@game.id) , class: "label label-primary" %>
            </h3>   
        </div>
        <div class="box-body">
          <div class="table-responsive">
            <div id="example_wrapper" class="dataTables_wrapper" role="grid">
              <div class="dataTables_length" id="example_length">
              </div>
              <div id="example_filter" class="dataTables_filter pull-right">
              </div>
              <table aria-describedby="example_info" class="table table-bordered table-hover table-striped display dataTable" id="example">
                <thead>
                  <tr role="row">
                    <th aria-label="Business name: activate to sort column ascending" aria-sort="ascending" style="width: 178px;" colspan="1" rowspan="1" aria-controls="example" tabindex="0" role="columnheader" class="ver-align-top">Image</th>
                     <td><%=image_tag @game.game_image %></td>
                  </tr>
                  <tr role="row">
                    <th aria-label="Business name: activate to sort column ascending" aria-sort="ascending" style="width: 178px;" colspan="1" rowspan="1" aria-controls="example" tabindex="0" role="columnheader"  > Name</th>
                    <td><%= @game.name %></td>
                  </tr>

                  <tr role="row">
                    <th aria-label="Business name: activate to sort column ascending" aria-sort="ascending" style="width: 178px;" colspan="1" rowspan="1" aria-controls="example" tabindex="0" role="columnheader"  > Description</th>
                    <td><%= @game.description %></td>
                  </tr>
              
                  <tr role="row">
                    <th aria-label="Business name: activate to sort column ascending" aria-sort="ascending" style="width: 178px;" colspan="1" rowspan="1" aria-controls="example" tabindex="0" role="columnheader"  >Interval Sec</th>
                     <td><%= @game.interval_sec %></td>

                  </tr>
                     
                  <tr role="row">
                    <th aria-label="Business name: activate to sort column ascending" aria-sort="ascending" style="width: 178px;" colspan="1" rowspan="1" aria-controls="example" tabindex="0" role="columnheader">Number of Player</th>
                     <td><%= @game.num_of_player %></td>
                  </tr>

                  <tr role="row">
                    <th aria-label="Business name: activate to sort column ascending" aria-sort="ascending" style="width: 178px;" colspan="1" rowspan="1" aria-controls="example" tabindex="0" role="columnheader" class="ver-align-top">Winning Parts</th>
                     <td>
                        <% @game.winning_parts.each do  |winning_part| %>
                          <%=winning_part.text_panel %><br/>
                        <% end %>
                     </td>
                  </tr>
                </thead>
              </table>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </div>
</section>
<br>